region             = "ap-south-1"
project            = "myapp"
environment        = "dev"
cluster_name       = "eks-cluster"
node_instance_type = "m7i-flex.large"
kubernetes_version = "1.35"
vpc_cidr           = "10.0.0.0/16"